### ISSUE TITLE
List Item component (logic)

### ISSUE THREAD

**Issue by elvykiung** [elvykiung/indoorplants#7]
# Feature

- [x] api call to database get data and present it ( 2 col, pics & detail_
- pics
- Sientific name
- Common Name
- icons on water need, light need and growth care need level

**Comment by karmitage** [comment]
I'm confused about what this is for - wouldn't it be encompassed in the Search and Discover features we already have issues for?

**Comment by elvykiung** [comment]
list item component is usable component in both discover and search page. on both page they just need to call this component in their component.
